"""
constants.
"""

from datetime import timedelta

from custom_components.citymind_water_meter.common.enums import AlertChannel, EntityKeys
from homeassistant.const import CONF_EMAIL, CONF_PASSWORD

VERSION = "1.0.0"

ATTR_FRIENDLY_NAME = "friendly_name"
ATTR_ACTIONS = "actions"
ACTION_ENTITY_SET_NATIVE_VALUE = "set_native_value"
ACTION_ENTITY_SELECT_OPTION = "select_option"
ENTITY_CONFIG_ENTRY_ID = "entry_id"
DOMAIN = "citymind_water_meter"
DEFAULT_NAME = "CityMind"

PROVIDER = "Read Your Meter Pro"

CONFIGURATION_FILE = f"{DOMAIN}.config.json"
INVALID_TOKEN_SECTION = "https://github.com/maorcc/citymind_water_meter#invalid-token"
STORAGE_DATA_KEY = "key"

SIGNAL_METER_ADDED = f"{DOMAIN}_METER_ADDED_SIGNAL"
SIGNAL_ACCOUNT_ADDED = f"{DOMAIN}_ACCOUNT_ADDED_SIGNAL"
SIGNAL_DATA_CHANGED = f"{DOMAIN}_DATA_CHANGED_SIGNAL"

SIGNAL_API_STATUS = f"{DOMAIN}_API_STATUS_SIGNAL"

ADD_COMPONENT_SIGNALS = [SIGNAL_METER_ADDED, SIGNAL_ACCOUNT_ADDED]

DATA_KEYS = [CONF_EMAIL, CONF_PASSWORD]

RECONNECT_INTERVAL = timedelta(minutes=1)
WEEKDAY_UPDATE_DATA_INTERVAL = timedelta(minutes=10)
WEEKEND_UPDATE_DATA_INTERVAL = timedelta(hours=3)
UPDATE_ENTITIES_INTERVAL = timedelta(minutes=1)

UPDATE_DATA_INTERVALS: dict[bool | None, timedelta] = {
    True: WEEKEND_UPDATE_DATA_INTERVAL,
    False: WEEKDAY_UPDATE_DATA_INTERVAL,
}

API_URL = "https://eu-customerportal-api.harmonyencoremdm.com"

CITY_MIND_WEBSITE = "https://rym-pro.com"

ENDPOINT_PARAMETER_METER_ID = "meter_id"
ENDPOINT_PARAMETER_YESTERDAY = "yesterday"
ENDPOINT_PARAMETER_TODAY = "today"
ENDPOINT_PARAMETER_LAST_DAY_MONTH = "last_day_month"
ENDPOINT_PARAMETER_MUNICIPALITY_ID = "municipality_id"
ENDPOINT_PARAMETER_CURRENT_MONTH = "current_month"
ENDPOINT_PARAMETER_ALERT_TYPE = "alert_type"

ENDPOINT_CONSUMER = f"{API_URL}/consumer"

ENDPOINT_CONSUMPTION = f"{API_URL}/consumption"

ENDPOINT_MUNICIPALS_OLD = f"{API_URL}/municipals"
ENDPOINT_MUNICIPALS_NEW = f"{API_URL}/municipality"

ENDPOINT_LOGIN = f"{ENDPOINT_CONSUMER}/login"

ENDPOINT_ME = f"{ENDPOINT_CONSUMER}/me"
ENDPOINT_METERS = f"{ENDPOINT_CONSUMER}/meters"
ENDPOINT_UNITS = f"{ENDPOINT_MUNICIPALS_OLD}/h1/measurmentunits"
ENDPOINT_CUSTOMER_SERVICE = f"{ENDPOINT_MUNICIPALS_OLD}/municipalCustomerService"
ENDPOINT_ALERTS_FOR_SETTINGS = f"{ENDPOINT_CONSUMER}/alertsForSettings"

ENDPOINT_LAST_READ = f"{ENDPOINT_CONSUMPTION}/last-read"
ENDPOINT_CONSUMPTION_DAILY = (
    f"{ENDPOINT_CONSUMPTION}/daily/{{meter_id}}/{{yesterday}}/{{today}}"
)
ENDPOINT_CONSUMPTION_MONTHLY = f"{API_URL}/v1.1/consumption/monthly/{{meter_id}}/{{current_month}}/{{last_day_month}}"
ENDPOINT_VACATIONS = f"{ENDPOINT_CONSUMER}/vacations"
ENDPOINT_MY_ALERTS = f"{ENDPOINT_CONSUMER}/myalerts"
ENDPOINT_MY_ALERTS_SETTINGS = f"{ENDPOINT_CONSUMER}/myalerts/settings"
ENDPOINT_MY_MESSAGES = f"{ENDPOINT_MUNICIPALS_NEW}/{{municipality_id}}/messages"
ENDPOINT_MY_MESSAGE_SUBJECTS = f"{ENDPOINT_MY_MESSAGES}/message-subjects"
ENDPOINT_CONSUMPTION_LOW_RATE_LIMIT = f"{ENDPOINT_CONSUMPTION}/Low-Rate-Limit"
ENDPOINT_CONSUMPTION_FORECAST = f"{ENDPOINT_CONSUMPTION}/forecast/{{meter_id}}"
ENDPOINT_MY_ALERTS_SETTINGS_UPDATE = f"{ENDPOINT_MY_ALERTS}/settings/{{alert_type}}"

API_DATA_SECTION_ME = "me"
API_DATA_SECTION_METERS = "meters"
API_DATA_SECTION_CUSTOMER_SERVICE = "customer-service"
API_DATA_SECTION_LAST_READ = "last-read"
API_DATA_SECTION_VACATIONS = "vacations"
API_DATA_SECTION_MY_ALERTS = "my-alerts"
API_DATA_SECTION_MY_MESSAGES = "my-messages"
API_DATA_SECTION_CONSUMPTION_DAILY = "consumption-daily"
API_DATA_SECTION_CONSUMPTION_MONTHLY = "consumption-monthly"
API_DATA_SECTION_CONSUMPTION_FORECAST = "consumption-forecast"
API_DATA_SECTION_SETTINGS = "settings"

CUSTOMER_SERVICE_PHONE_NUMBER = "phoneNumber"
CUSTOMER_SERVICE_DESCRIPTION = "description"
CUSTOMER_SERVICE_PHONE_MUNICIPAL_ID = "municipalID"
CUSTOMER_SERVICE_EMAIL = "Email"

METER_COUNT = "meterCount"
METER_SERIAL_NUMBER = "meterSn"
METER_FULL_ADDRESS = "fullAddress"

LAST_READ_METER_COUNT = METER_COUNT
LAST_READ_METER_ID = "meterId"
LAST_READ_VALUE = "read"

ME_FIRST_NAME = "firstName"
ME_LAST_NAME = "lastName"
ME_ACCOUNT_NUMBER = "accountNumber"
ME_PHONE_NUMBER_SECTION = "phoneNumber"
ME_COUNTRY_CODE = "countryCode"
ME_PHONE_NUMBER = "phoneNumber"
ME_ADDITIONAL_PHONE_NUMBER = "AdditionalPhoneNumber"
ME_MUNICIPAL_ID = "municipalId"

CONSUMPTION_METER_COUNT = METER_COUNT
CONSUMPTION_VALUE = "cons"
CONSUMPTION_DATA = "consumptionData"
CONSUMPTION_DATE = "consDate"

CONSUMPTION_ESTIMATION_TYPE = "estimationType"
CONSUMPTION_METER_STATUS_DESC = "meterStatusDesc"

CONSUMPTION_FORECAST_ESTIMATED_CONSUMPTION = "estimatedConsumption"

SETTINGS_ALERT_TYPE_ID = "alertTypeId"
SETTINGS_MEDIA_TYPE_ID = "mediaTypeId"

ENDPOINT_DATA_INITIALIZE = {
    API_DATA_SECTION_ME: ENDPOINT_ME,
    API_DATA_SECTION_METERS: ENDPOINT_METERS,
    API_DATA_SECTION_CUSTOMER_SERVICE: ENDPOINT_CUSTOMER_SERVICE,
}

ENDPOINT_DATA_UPDATE = {
    API_DATA_SECTION_LAST_READ: ENDPOINT_LAST_READ,
    API_DATA_SECTION_VACATIONS: ENDPOINT_VACATIONS,
    API_DATA_SECTION_MY_ALERTS: ENDPOINT_MY_ALERTS,
    API_DATA_SECTION_SETTINGS: ENDPOINT_MY_ALERTS_SETTINGS,
}


ENDPOINT_DATA_UPDATE_PER_METER = {
    API_DATA_SECTION_CONSUMPTION_DAILY: ENDPOINT_CONSUMPTION_DAILY,
    API_DATA_SECTION_CONSUMPTION_MONTHLY: ENDPOINT_CONSUMPTION_MONTHLY,
    API_DATA_SECTION_CONSUMPTION_FORECAST: ENDPOINT_CONSUMPTION_FORECAST,
}

ENDPOINT_DATA_RELOAD = {API_DATA_SECTION_SETTINGS: ENDPOINT_MY_ALERTS_SETTINGS}

PH_TODAY = "[PH_TODAY]"
PH_YESTERDAY = "[PH_YESTERDAY]"
PH_CURRENT_MONTH = "[PH_CURRENT_MONTH]"
PH_LAST_DAY_MONTH = "[PH_LAST_DAY_MONTH]"
PH_METER = "[PH_METER_ID]"
PH_MUNICIPALITY = "[PH_MUNICIPALITY]"

LOGIN_EMAIL = "email"
LOGIN_PASSWORD = "pw"
LOGIN_DEVICE_ID = "deviceId"

DEVICE_ID = "home-assistant"
HA_NAME = "homeassistant"

API_DATA_TOKEN = "token"
API_DATA_ERROR_CODE = "code"
API_DATA_ERROR_REASON = "error"

API_DATA_LAST_UPDATE = "last-update"

ERROR_REASON_INVALID_CREDENTIALS = 5060

API_HEADER_TOKEN = "x-access-token"

ICON_ALERT_MODES = {}

STORAGE_API_LIST = "list"
STORAGE_API_DATA_API = "api"

STORAGE_API_DATA = [STORAGE_API_DATA_API]

FORMAT_DATE_ISO = "%Y-%m-%d"
FORMAT_DATE_YEAR_MONTH = "%Y-%m"

WEEKEND_DAYS = ["Friday", "Saturday"]

ATTR_MEDIA_TYPES = "media_type"
ATTR_ALERT_TYPES = "alert_type"
ATTR_MONTHLY_CONSUMPTION = "Monthly Consumption"
ATTR_LOW_RATE_CONSUMPTION = "Low Rate Consumption"
ATTR_HIGH_RATE_CONSUMPTION = "High Rate Consumption"
ATTR_LOW_RATE_COST = "Low Rate Cost"
ATTR_HIGH_RATE_COST = "High Rate Cost"
ATTR_SEWAGE_COST = "Sewage Cost"
ATTR_TOTAL_COST = "Monthly Cost"

STORAGE_DATA_METERS = "meters"
STORAGE_DATA_METER_LOW_RATE_CONSUMPTION_THRESHOLD = "low_rate_consumption_threshold"
STORAGE_DATA_METER_LOW_RATE_COST = "low_rate_cost"
STORAGE_DATA_METER_HIGH_RATE_COST = "high_rate_cost"
STORAGE_DATA_METER_SEWAGE_COST = "sewage_cost"

DEFAULT_LOW_RATE_CONSUMPTION_THRESHOLD = 3.5
DEFAULT_LOW_RATE_COST = 7.955
DEFAULT_HIGH_RATE_COST = 14.6
DEFAULT_SEWAGE_COST = 0

DEFAULT_METER_CONFIG = {
    STORAGE_DATA_METER_LOW_RATE_CONSUMPTION_THRESHOLD: DEFAULT_LOW_RATE_CONSUMPTION_THRESHOLD,
    STORAGE_DATA_METER_LOW_RATE_COST: DEFAULT_LOW_RATE_COST,
    STORAGE_DATA_METER_HIGH_RATE_COST: DEFAULT_HIGH_RATE_COST,
    STORAGE_DATA_METER_SEWAGE_COST: DEFAULT_SEWAGE_COST,
}

UNIT_COST = "ILS/m³"

ALL_OPTIONS = [str(channel) for channel in list(AlertChannel)]
LEAK_OPTIONS = [AlertChannel.EMAIL, AlertChannel.ALL]

ALERT_OPTIONS = {
    EntityKeys.ALERT_EXCEEDED_THRESHOLD: ALL_OPTIONS,
    EntityKeys.ALERT_LEAK: LEAK_OPTIONS,
    EntityKeys.ALERT_LEAK_WHILE_AWAY: ALL_OPTIONS,
}
